language: cpp
sudo: required
dist: trusty


matrix:
  fast_finish: true
  include:
    - os: linux
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-6', 'cmake']
      env: CCOMPILER='gcc-6' CXXCOMPILER='g++-6'

    - os: linux
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5', 'cmake']
      env: CCOMPILER='gcc-5' CXXCOMPILER='g++-5'

    - os: linux
      addons:
        apt:
          sources: ['llvm-toolchain-precise-3.8']
          packages: ['clang-3.8', 'cmake']
      env: CCOMPILER='clang-3.8' CXXCOMPILER='clang++-3.8'

    # Waiting on Travis whitelisting 3.9, see https://github.com/travis-ci/apt-source-whitelist/issues/300
    #- os: linux
    #  addons:
    #    apt:
    #      sources: ['llvm-toolchain-precise-3.9']
    #      packages: ['clang-3.9']
    #  env: CCOMPILER='clang-3.9' CXXCOMPILER='clang++-3.9'

    - os: osx
      osx_image: xcode8
      env: CCOMPILER='clang' CXXCOMPILER='clang++'


before_install:
  - export CC=${CCOMPILER} CXX=${CXXCOMPILER}


install:
  - make
  - sudo make install

script:
  - echo "Nothing to run"
